import chatgptImporter from './tools/chatgpt/importer/chatgpt_importer';

async function testImporter() {
    // We get the key from the environment to avoid hardcoding it in the script,
    // though you can replace 'YOUR_API_KEY_HERE' literally if you prefer.

    const CHATGPT_API_KEY = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5MzQ0ZTY1LWJiYzktNDRkMS1hOWQwLWY5NTdiMDc5YmQwZSIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSJdLCJjbGllbnRfaWQiOiJhcHBfWDh6WTZ2VzJwUTl0UjNkRTduSzFqTDVnSCIsImV4cCI6MTc3MzE3Mjg1MSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7ImNoYXRncHRfYWNjb3VudF9pZCI6Ijc2Y2MzZmMwLTZiNTAtNDcyNS05YTA5LWNkNzcwOWFmZTA0YiIsImNoYXRncHRfYWNjb3VudF91c2VyX2lkIjoidXNlci1pU3VmekdMczZkS2hxZ1o5RkY0Z3V1aWVfXzc2Y2MzZmMwLTZiNTAtNDcyNS05YTA5LWNkNzcwOWFmZTA0YiIsImNoYXRncHRfY29tcHV0ZV9yZXNpZGVuY3kiOiJub19jb25zdHJhaW50IiwiY2hhdGdwdF9wbGFuX3R5cGUiOiJnbyIsImNoYXRncHRfdXNlcl9pZCI6InVzZXItaVN1ZnpHTHM2ZEtocWdaOUZGNGd1dWllIiwidXNlcl9pZCI6InVzZXItaVN1ZnpHTHM2ZEtocWdaOUZGNGd1dWllIn0sImh0dHBzOi8vYXBpLm9wZW5haS5jb20vcHJvZmlsZSI6eyJlbWFpbCI6InB5ZXJzY2hyaXNAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJpYXQiOjE3NzIzMDg4NTAsImlzcyI6Imh0dHBzOi8vYXV0aC5vcGVuYWkuY29tIiwianRpIjoiNzdjMTU1OTYtNmY5NC00YjhiLWJhN2UtODE3YTk2ODllYmYxIiwibmJmIjoxNzcyMzA4ODUwLCJwd2RfYXV0aF90aW1lIjoxNzcyMzA4ODQ5Nzc5LCJzY3AiOlsib3BlbmlkIiwiZW1haWwiLCJwcm9maWxlIiwib2ZmbGluZV9hY2Nlc3MiLCJtb2RlbC5yZXF1ZXN0IiwibW9kZWwucmVhZCIsIm9yZ2FuaXphdGlvbi5yZWFkIiwib3JnYW5pemF0aW9uLndyaXRlIl0sInNlc3Npb25faWQiOiJhdXRoc2Vzc183YkdYSXR5QVAxVEFCc0FGNzJjSkJBd0ciLCJzdWIiOiJnb29nbGUtb2F1dGgyfDEwNDcxMTk3NDc2MjQ1NDcxOTU3OCJ9.peKWIskKWPNlRTzCoISrPDQYICMgn7Ntc7f1ngt5UEJP4mpa234JX7MrcgzTAQBR35uSYju1eKLeGML-tzDTaY7tlTyTzqTGXpAWCF5l6hIpc5q2zjNNTXt7FOXREEs2bbmRkcTPGEktXDNEVVMdzYGFXiN5hGWd10k9mN492OgcMwC6ji64KKQOXvz9lbFPF9v_w8Cu4mSd3bkxDDlA2-X5z9Qix5qkt4OxU6u-iKAXv5ZxbpRm_3KcLeND_BrE_1-VQAmtrw-Xxnep8Y7IcuYI5ze_z7PseqlDuupHy5S029ztWR2gjwpjeBmDJG5zIRMvnJ--vdFef8nPznyYl_FdVsQs0fjwjAHH_4jL_rSV4T_oNNlEKO_inyzJJ8mNtdmS6tME9e30y1JAQQWc5PqXquyfvrcu3Lj5fzR6ofomu7d5L9HElwscR6uF9QX_gYGCbB6KthNk6NUxWsCMKzH83Lw3QA_0xVM_eu8Z6_IgXqD136UDD1wQp-Qi-oZmlq3OkC-qFn4ndUmk1qVWOg2Y1r1kMbGUQ5WMUIaCdsZHLAqtXDbkFc-cc6_bXuNbtU8E4JXPBKjKvd6DH06MVuBpwVa3T9MeAy2I5-dnUb6hNOhOoAZXXw3Cs6b7Asl4kJyCUPMms2HXoRxMA9k9r4d7vJClsF-KwfTLvQyfsZY"

    const apiKey = process.env.CHATGPT_API_KEY || CHATGPT_API_KEY;
    const outputDir = 'test_chatgpt_import';

    console.log(`Running ChatGPT Importer Tool...`);
    console.log(`Testing with output directory: workspace/${outputDir}`);

    // Call the handler directly the same way the agent does
    const result = await chatgptImporter.handler({ authToken: apiKey, outputDir });

    console.log('\n--- Result from handler ---');
    console.log(JSON.stringify(result, null, 2));
}

testImporter().catch(console.error);
